# Generated by Django 3.0.5 on 2020-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Warranty',
            field=models.CharField(default='1 Year Manufacturing Domestic Warranty ', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
